### PR TITLE
doc: completed public API javadocs

### PR DESCRIPTION
**Pull request by mgarciavaadin**
## Description

Completing public API Javadocs

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.
- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by czp13** [comment]
I will fix conflicts and add some changes to the doc as we discussed in daily, in the morning probably.

**Review by czp13 — CHANGES_REQUESTED** [review]
As we discussed in Slack and dailies:
- it would be nice to add the params as well for the methods, 
- and give some words about what the params do, purpose, meaning of them

So for example here:
```java
 /**
     * Generates a prompt based on the input, the target objectmap and extra instructions.
     */
    public String getPromptTemplate(String input, Map<String, Object> objectMap, Map<String, String> typesMap, HashMap<Component, String> componentInstructions, ArrayList<String> contextInstructions);
```
We could explain typesMap and the difference between components and contextInstructions.  And use @param for proper JavaDoc generation.

Similarly to all other public methods, we could add @param and params explanations I feel :).

Otherwise, this is good, just a bit more detail, and info would be nicer.

And lastly, conflict needs to be fixed before we can merge, mark this with changes needed, just to not accidentally merge :D

**Comment by mgarciavaadin** [comment]
Updated javadoc, @czp13 please review again whenever you can

**Review by czp13 — APPROVED** [review]
This is a much more solid, detailed version of Javadocs. Thank you for the improvements and examples, params, results 🙇

**Pull request merged**
